mysite/movies/urls.py
# movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:movie_pk>/update', views.update, name="update"),
    path('<int:movie_pk>/', views.detail, name="detail"),
    path('<int:movie_pk>/delete', views.delete, name="delete"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

mysite/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=150)
    title_en = models.CharField(max_length=150)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=150)
    watch_grade = models.CharField(max_length=150)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

mysite/movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title', 'title_en', 'audience', 'open_date', 'genre', 'watch_grade', 'score', 'poster_url', 'description']

mysite/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MovieForm
from .models import Movie

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies' : movies
    }
    return render(request, 'movies/index.html', context)

def create(request):
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:index')

    else:
        form = MovieForm()
    context = {
        'form' : form
    }
    return render(request, 'movies/form.html', context)

def update(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method=="POST":
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:index')
    else:
        form = MovieForm(instance=movie)
    context={
        'form':form
    }
    return render(request, 'movies/form.html', context)

def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    context={
        'movie' : movie
    }
    return render(request, 'movies/detail.html', context)

def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    movie.delete()
    return redirect('movies:index')

mysite/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <h1>{{ movie.title }}</h1>
  <h4>{{ movie.title_en }}</h4>
  <hr>
  <h3>누적관객수 : {{ movie.audience }}명</h3>
  개봉일 : {{ movie.open_date }}</p>
  <p>장르 : {{ movie.genre }}</p>
  <p>관람등급 : {{ movie.watch_grade }}</p>
  <p>평점 : {{ movie.score }}</p>
  <img src="{{ movie.poster_url }}" width="40%" height="30%">
  <h3>영화 소개 : {{ movie.description }}</h3>

  <h4><a href="{% url 'movies:update' movie.pk %}">글 수정</a></h4> &nbsp;
  <h4><a href="{% url 'movies:delete' movie.pk %}"> 글 삭제하기</a></h4> &nbsp;
  <h4><a href="{% url 'movies:index' %}"> [back]</a></h4> &nbsp;
{% endblock %}

mysite/movies/templates/movies/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
{% if request.resolver_match.url_name == 'create' %}
  <h1>글 생성</h1>
{% else %}
  <h1>글 수정</h1>
{% endif %}
<hr>

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
    Submit
  </button>
  {% endbuttons %}
</form>

<a href="{% url 'movies:index' %}">index</a>
{% endblock %}

mysite/movies/templates/movies/index.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
{% for movie in movies %}
  title : <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a> , score : {{ movie.score }}
  <hr>
{% endfor %}

<h2><a href="{% url 'movies:create' %}">영화 추가하기</a></h2>
{% endblock %}

mysite/mysite/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>
</html>